
import React from 'react';
import CityPage from '@/components/CityPage';

const Telford = () => {
  const description = "JonesCo Seamless Gutter Systems provides exceptional seamless gutter services in Telford. We specialize in seamless gutter installation, gutter repair, gutter cleaning, and custom gutter solutions to ensure your home is protected from water damage. Our experienced team delivers top-quality workmanship and reliable service in Telford.";
  const keywords = [
    "commercial gutter installation near Telford",
    "seamless gutter company near Telford",
    "seamless gutters companies near Telford",
    "gutter repair contractors near Telford",
    "seamless gutter contractors near Telford",
    "seamless gutter installation near Telford",
    "seamless gutter installer near Telford",
    "seamless guttering companies near Telford",
    "seamless gutters contractors near Telford",
    "seamless gutters installation near Telford",
    "seamless gutters installers near Telford",
    "seamless rain gutters near Telford",
    "custom gutters near Telford",
    "gutter companies around Telford",
    "gutter contractor near Telford",
    "gutter contractors near Telford",
    "gutter guards installers near Telford",
    "gutter price calculator Telford",
    "gutters and siding contractors near Telford",
    "handyman gutter repair near Telford",
    "rain gutter contractor near Telford",
    "rain gutter contractors near Telford",
    "rain gutters contractors near Telford",
    "roof gutter installers near Telford",
    "seamless gutter companies near Telford",
    "seamless gutter contractor near Telford",
    "seamless gutter installers near Telford",
    "seamless gutters installed near Telford",
    "seamless gutters near Telford",
    "seemless gutters near Telford",
    "siding and gutters near Telford",
    "gutter business near Telford",
    "gutter guards installed near Telford",
    "gutter install near Telford",
    "guttering contractors near Telford",
    "gutters and siding near Telford",
    "gutters contractor near Telford",
    "gutters contractors near Telford",
    "gutters install near Telford",
    "roof and gutter contractors near Telford",
    "seamless gutter near Telford",
    "seamless guttering near Telford",
    "top rated gutter companies near Telford",
    "youtube gutter installation Telford",
    "continuous gutters near Telford",
    "gutter instalation near Telford",
    "gutter install companies near Telford",
    "gutter installation companies near Telford",
    "gutter installation company near Telford",
    "gutter installation contractors near Telford",
    "gutter installer near Telford",
    "gutter installers near Telford",
    "gutter replacement companies near Telford",
    "gutter service near Telford",
    "guttering installation near Telford",
    "guttering installers near Telford",
    "gutters installation near Telford",
    "gutters installed near Telford",
    "mini gutter Telford",
    "small gutter Telford",
    "small gutters Telford",
    "where to buy mobile home gutters Telford",
    "tools for gutter installation Telford",
    "window gutters Telford",
    "large rain gutters Telford",
    "2 inch gutter Telford",
    "menards downspouts Telford",
    "rain gutters at menards Telford",
    "downspout extension menards Telford",
    "downspout repair near Telford",
    "gares de casa Telford",
    "wide rain gutters Telford",
    "16 ft gutter lowe's Telford",
    "mini gutters lowe's Telford",
    "gutter parts home depot Telford",
    "gutter roof Telford",
    "mini gutters Telford",
    "plastic rain gutters home depot Telford",
    "roofing gutter Telford",
    "plastic gutters home depot Telford",
    "gutter screws home depot Telford",
    "add downspout to rain gutter Telford",
    "aluminum rain gutters home depot Telford",
    "gutter downspouts at lowes Telford",
    "aluminum gutters home depot Telford",
    "gutter downspout installation Telford",
    "rain gutter company near Telford",
    "roof gutter repair near Telford",
    "seamless gutter price calculator Telford",
    "affordable gutters near Telford",
    "local gutter company Telford",
    "local rain gutter companies Telford",
    "water gutter Telford",
    "downspouts at lowes Telford",
    "gutters installers near Telford",
    "roofing and gutters near Telford",
    "gutter fixing near Telford",
    "home depot gutters and downspouts Telford",
    "homedepot gutters Telford",
    "rain gutters repair near Telford"
  ];

  return (
    <CityPage
      city="Telford"
      county="Washington"
      description={description}
      keywords={keywords}
    />
  );
};

export default Telford;
