
import React from 'react';
import CountyPage from '@/components/CountyPage';

const Washington = () => {
  const county = "Washington";
  const cities = ["Johnson City","Jonesborough","Limestone","Telford"];
  const description = "JonesCo Seamless Gutter Systems provides exceptional seamless gutter services in Washington County, TN. Our team specializes in gutter installation, gutter repair, gutter cleaning, and custom gutter solutions to ensure your home is protected from water damage. We use the highest quality materials and techniques to deliver top-notch service in Washington County.";
  const keywords = [
    "commercial gutter installation near Washington County",
    "seamless gutter company near Washington County",
    "seamless gutters companies near Washington County",
    "gutter repair contractors near Washington County",
    "seamless gutter contractors near Washington County",
    "seamless gutter installation near Washington County",
    "seamless gutter installer near Washington County",
    "seamless guttering companies near Washington County",
    "seamless gutters contractors near Washington County",
    "seamless gutters installation near Washington County",
    "seamless gutters installers near Washington County",
    "seamless rain gutters near Washington County",
    "custom gutters near Washington County",
    "gutter companies around Washington County",
    "gutter contractor near Washington County",
    "gutter contractors near Washington County",
    "gutter guards installers near Washington County",
    "gutter price calculator Washington County",
    "gutters and siding contractors near Washington County",
    "handyman gutter repair near Washington County",
    "rain gutter contractor near Washington County",
    "rain gutter contractors near Washington County",
    "rain gutters contractors near Washington County",
    "roof gutter installers near Washington County",
    "seamless gutter companies near Washington County",
    "seamless gutter contractor near Washington County",
    "seamless gutter installers near Washington County",
    "seamless gutters installed near Washington County",
    "seamless gutters near Washington County",
    "seemless gutters near Washington County",
    "siding and gutters near Washington County",
    "gutter business near Washington County",
    "gutter guards installed near Washington County",
    "gutter install near Washington County",
    "guttering contractors near Washington County",
    "gutters and siding near Washington County",
    "gutters contractor near Washington County",
    "gutters contractors near Washington County",
    "gutters install near Washington County",
    "roof and gutter contractors near Washington County",
    "seamless gutter near Washington County",
    "seamless guttering near Washington County",
    "top rated gutter companies near Washington County",
    "youtube gutter installation Washington County",
    "continuous gutters near Washington County",
    "gutter instalation near Washington County",
    "gutter install companies near Washington County",
    "gutter installation companies near Washington County",
    "gutter installation company near Washington County",
    "gutter installation contractors near Washington County",
    "gutter installer near Washington County",
    "gutter installers near Washington County",
    "gutter replacement companies near Washington County",
    "gutter service near Washington County",
    "guttering installation near Washington County",
    "guttering installers near Washington County",
    "gutters installation near Washington County",
    "gutters installed near Washington County",
    "mini gutter Washington County",
    "small gutter Washington County",
    "small gutters Washington County",
    "where to buy mobile home gutters Washington County",
    "tools for gutter installation Washington County",
    "window gutters Washington County",
    "large rain gutters Washington County",
    "2 inch gutter Washington County",
    "menards downspouts Washington County",
    "rain gutters at menards Washington County",
    "downspout extension menards Washington County",
    "downspout repair near Washington County",
    "gares de casa Washington County",
    "wide rain gutters Washington County",
    "16 ft gutter lowe's Washington County",
    "mini gutters lowe's Washington County",
    "gutter parts home depot Washington County",
    "gutter roof Washington County",
    "mini gutters Washington County",
    "plastic rain gutters home depot Washington County",
    "roofing gutter Washington County",
    "plastic gutters home depot Washington County",
    "gutter screws home depot Washington County",
    "add downspout to rain gutter Washington County",
    "aluminum rain gutters home depot Washington County",
    "gutter downspouts at lowes Washington County",
    "aluminum gutters home depot Washington County",
    "gutter downspout installation Washington County",
    "rain gutter company near Washington County",
    "roof gutter repair near Washington County",
    "seamless gutter price calculator Washington County",
    "affordable gutters near Washington County",
    "local gutter company Washington County",
    "local rain gutter companies Washington County",
    "water gutter Washington County",
    "downspouts at lowes Washington County",
    "gutters installers near Washington County",
    "roofing and gutters near Washington County",
    "gutter fixing near Washington County",
    "home depot gutters and downspouts Washington County",
    "homedepot gutters Washington County",
    "rain gutters repair near Washington County"
  ];

  return (
    <CountyPage county={county} cities={cities} description={description} keywords={keywords} />
  );
};

export default Washington;
